package com.noteapp.theme

object Icons {
    const val MENU = "☰"
    const val CLOSE = "✕"
    const val ADD = "+"
    const val SEARCH = "🔍"
    const val DELETE = "🗑️"
    const val BACK = "←"
    const val FORWARD = "→"
    const val TAG = "🏷️"
    const val EXPORT = "📤"
    const val PREVIEW = "👁️"
    const val RESTORE = "♻️"
    const val EMPTY_TRASH = "📭"
    const val NOTE_EMPTY = "📝"
    const val WARNING = "⚠️"
    const val INFO = "ℹ️"
    const val CHECK = "✓"
    const val SELECT_ALL = "☐"
    const val SELECTED = "☑"
    const val MORE = "⋯"
    const val CLEAR = "✕"
    const val HISTORY = "🕐"
    const val SAVE = "💾"
    const val SHARE = "📋"
    const val DRAG = "⠿"
    const val REFRESH = "🔄"
    const val PIN = "📍"
    const val SEARCH_SCOPE = "🔎"
}
